/**
 * CookieControl — Ad/tracker blocklist for declarativeNetRequest.
 * Curated list of common ad and tracking domains. Used when "Block ads" is on.
 */
const AD_BLOCK_DOMAINS = [
  'doubleclick.net',
  'googlesyndication.com',
  'googleadservices.com',
  'google-analytics.com',
  'googletagmanager.com',
  'googletagservices.com',
  '2mdn.net',
  'adservice.google.com',
  'pagead2.googlesyndication.com',
  'tpc.googlesyndication.com',
  'ads.youtube.com',
  'ad.youtube.com',
  'ads-api.youtube.com',
  'pubads.g.doubleclick.net',
  'googleads.g.doubleclick.net',
  'brain.fm',
  'myiq.com',
  'adnxs.com',
  'adsrvr.org',
  'advertising.com',
  'criteo.com',
  'criteo.net',
  'outbrain.com',
  'taboola.com',
  'mgid.com',
  'revcontent.com',
  'zedo.com',
  'adform.net',
  'adform.com',
  'adsymptotic.com',
  'adroll.com',
  'rubiconproject.com',
  'pubmatic.com',
  'openx.net',
  'contextweb.com',
  'casalemedia.com',
  'chartbeat.com',
  'newrelic.com',
  'hotjar.com',
  'fullstory.com',
  'crazyegg.com',
  'clicksor.com',
  'bidvertiser.com',
  'propellerads.com',
  'popads.net',
  'popcash.net',
  'adsterra.com',
  'exoclick.com',
  'trafficjunky.com',
  'juicyads.com',
  'media.net',
  'amazon-adsystem.com',
  'aax.amazon-adsystem.com',
  's.amazon-adsystem.com',
  'facebook.net',
  'connect.facebook.net',
  'analytics.facebook.com',
  'pixel.facebook.com',
  'tr.analytics.facebook.com',
  'snap.licdn.com',
  'px.ads.linkedin.com',
  'bat.bing.com',
  'ads.linkedin.com',
  'twitter.com/i/ads',
  'analytics.twitter.com',
  't.co',
  'ads.twitter.com',
  'pixel.twitter.com',
  'ads-api.twitter.com',
  'moatads.com',
  'scorecardresearch.com',
  'comscore.com',
  'quantserve.com',
  'quantcast.com',
  'demdex.net',
  'everesttech.net',
  'bluekai.com',
  'krxd.net',
  'liveramp.com',
  'rlcdn.com',
  'tribalfusion.com',
  'yieldmo.com',
  'spotxchange.com',
  'spotx.tv',
  'lijit.com',
  'sovrn.com',
  'beacon.affilinet.com',
  'tracking.affilinet.com',
  'impact.com',
  'sharethrough.com',
  'teads.tv',
  'smartadserver.com',
  'smartadserver.de',
  'nativo.com',
  'undertone.com',
  'districtm.io',
  'connextra.com',
  'adgrx.com',
  'adtech.de',
  'adtech.com',
  'adtech.jp',
  'adcolony.com',
  'inmobi.com',
  'tapad.com',
  'drawbridge.com',
  'crosswise.com',
  'advertising.yahoo.com',
  'ads.yahoo.com',
  'yimg.com',
  'gemini.yahoo.com',
  'adsymptotic.com',
  'exelator.com',
  'dpm.demdex.net',
  'ads.pubmatic.com',
  'gumgum.com',
  'improvedigital.com',
  'smaato.com',
  'vungle.com',
  'unity3d.com',
  'unityads.unity3d.com',
  'applovin.com',
  'chartboost.com',
  'fyber.com',
  'supersonic.com',
  'ironsrc.com',
  'mintegral.com',
  'ogury.io',
  'mopub.com',
  'ads.mopub.com',
  'bidswitch.net',
  'lifestreet.com',
  'somoaudience.com',
  'emxdgt.com',
  'sharethis.com',
  'addthis.com',
  'addthisedge.com',
  'sumome.com',
  'sumo.com',
  'olark.com',
  'zendesk.com',
  'intercom.io',
  'intercom.com',
  'segment.io',
  'segment.com',
  'mixpanel.com',
  'amplitude.com',
  'heapanalytics.com',
  'kissmetrics.com',
  'mouseflow.com',
  'luckyorange.com',
  'inspectlet.com',
  'pingdom.com',
  'nr-data.net',
  'nr-data.com',
  'omtrdc.net',
  '2o7.net',
  'omniroot.com',
  'akamaihd.net',
  'ads.akamaihd.net',
  'serving-sys.com',
  'burstnet.com',
  'adbrn.com',
  'adition.com',
  'adgrx.com',
  'adhigh.net',
  'adnium.com',
  'adobe.com/demdex',
  'demdex.net',
  'omtrdc.net',
  'everesttech.net',
  'conviva.com',
  'tvsquared.com',
  'nielsen.com',
  'nielsen-networks.com',
  'imrworldwide.com',
  'secure-ds.serving-sys.com',
  'atwola.com',
  'advertising.yahoo.com',
  'yimg.com',
  'ads.linkedin.com',
  'px.ads.linkedin.com',
  'snap.licdn.com',
  'ads.reddit.com',
  'events.reddit.com',
  'pixel.reddit.com',
  'ads.pinterest.com',
  'ct.pinterest.com',
  's.pinimg.com',
  'tiktok.com/i18n/pixel',
  'analytics.tiktok.com',
  'ads.tiktok.com',
  'video-ad-stats.googlevideo.com',
  'ads.yimg.com',
  'fls.doubleclick.net',
  'static.doubleclick.net',
  'partner.googleadservices.com',
  's.ytimg.com/shell',
  'i.ytimg.com/shell',
  'redirector.googlevideo.com',
  'www.google.com/pagead',
  'tpc.google.com',
  'adclick.g.doubleclick.net',
  'prebid.org',
  'prebid.adnxs.com',
  'prebid-server.rubiconproject.com',
  'indexexchange.com',
  'ix.media.net',
  'triplelift.com',
  'criteo.net',
  'conversantmedia.com',
  'rhythmone.com',
  'distroscale.com',
  'kargo.com',
  'yieldbot.com',
  '33across.com',
  'lijit.com',
  'e-planning.net',
  'adzerk.net',
  'ads.adzerk.net',
  'carbonads.com',
  'carbonads.net',
  'buysellads.com',
  'adnetwork.net',
  'advertising-api.com',
  'tremorvideo.com',
  'spotx.tv',
  'freewheel.com',
  'freewheel.mdx.tv',
  'stickyadstv.com',
  'springserve.com',
  'lunamedia.io',
  'synacor.com',
  'readpeak.com',
  'zergnet.com',
  'content.ad',
  'content-ad.com',
  'adblade.com',
  'gravity.com',
  'primis.tech',
  'video.unrulymedia.com',
  'bounceexchange.com',
  'bidtellect.com',
  'sonobi.com',
  'lockerdome.com',
  'w55c.net',
  'simility.com',
  'securepubads.g.doubleclick.net',
  'fundingchoicesmessages.google.com',
  'ad.doubleclick.net',
  'stats.g.doubleclick.net',
];

const YOUTUBE_REGEX_RULES = [
  { regex: /youtube\.com\/.*(pagead|pageadview)/, types: ['script', 'xmlhttprequest', 'sub_frame', 'other'] },
  { regex: /youtube\.com\/api\/stats\/ads/, types: ['xmlhttprequest', 'other'] },
  { regex: /youtube\.com\/.*ptracking/, types: ['xmlhttprequest', 'other'] },
  { regex: /youtube\.com\/.*(ad_module|adsense|get_video_info.*[\?&]ad_)/, types: ['script', 'xmlhttprequest', 'other'] },
  { regex: /youtube\.com\/youtubei\/v1\/.*(player_ad|ad_)/, types: ['xmlhttprequest', 'other'] },
  { regex: /googlevideo\.com\/.*[\?&](oad|ctier)=/, types: ['media', 'xmlhttprequest', 'other'] },
];

const AD_BLOCK_RULE_IDS = Object.freeze({
  MIN: 1,
  MAX: AD_BLOCK_DOMAINS.length + YOUTUBE_REGEX_RULES.length,
});

/**
 * Build declarativeNetRequest rules to block requests to the ad/tracker domains and YouTube ad paths.
 * @returns {Array<{id: number, priority: number, action: object, condition: object}>}
 */
function getAdBlockRules() {
  const resourceTypes = [
    'script', 'image', 'xmlhttprequest', 'sub_frame', 'main_frame',
    'stylesheet', 'font', 'media', 'websocket', 'other'
  ];
  const domainRules = AD_BLOCK_DOMAINS.map((domain, i) => ({
    id: AD_BLOCK_RULE_IDS.MIN + i,
    priority: 1,
    action: { type: 'block' },
    condition: {
      urlFilter: `||${domain}^`,
      resourceTypes,
    },
  }));
  const youtubeRules = YOUTUBE_REGEX_RULES.map((r, i) => ({
    id: AD_BLOCK_RULE_IDS.MIN + AD_BLOCK_DOMAINS.length + i,
    priority: 2,
    action: { type: 'block' },
    condition: {
      regexFilter: r.regex.source,
      resourceTypes: r.types,
    },
  }));
  return domainRules.concat(youtubeRules);
}
